#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-bareos-update';

event_actions($event, qw(
             initialize-default-databases 00
             nethserver-bareos-create-postgresql-database 10
             nethserver-bareos-enablerepo 10
));

event_templates($event, qw(
                /etc/bareos/bareos-dir.d/catalog/MyCatalog.conf
                /etc/httpd/conf.d/default-virtualhost.inc
                /etc/httpd/conf.d/bareos-webui.conf
                /etc/httpd/conf.d/zzz_bareos-webui.conf
                /etc/opt/rh/rh-php73/php-fpm.d/bareos.conf
                /etc/bareos-webui/directors.ini
                /etc/bareos/bareos-dir.d/console/pam-console.conf
                /etc/bareos/bareos-dir.d/user/admin-web-ui.conf
));

event_services($event, qw(
               bareos-dir restart
               bareos-sd  restart
               bareos-fd  restart
               httpd      reload
               rh-php73-php-fpm restart 
));

$event = 'nethserver-bareos-save';

event_templates($event, qw(
                /etc/bareos/bareos-dir.d/catalog/MyCatalog.conf
                /etc/httpd/conf.d/default-virtualhost.inc
                /etc/httpd/conf.d/bareos-webui.conf
                /etc/httpd/conf.d/zzz_bareos-webui.conf
                /etc/opt/rh/rh-php73/php-fpm.d/bareos.conf
                /etc/bareos-webui/directors.ini
                /etc/bareos/bareos-dir.d/console/pam-console.conf
                /etc/bareos/bareos-dir.d/user/admin-web-ui.conf
));
event_services($event, qw(
               bareos-dir restart
               bareos-sd  restart
               bareos-fd  restart
               httpd      reload
               rh-php73-php-fpm restart 
));


#
# pre-backup-data
#

$event = 'pre-backup-data';

event_actions($event, qw(
             nethserver-bareos-dump 50
));

#
# post-restore-data
#

$event = 'post-restore-data';
event_actions($event, qw(
             nethserver-bareos-restore 50
));
event_services($event, qw(
               bareos-dir restart
               bareos-sd  restart
               bareos-fd  restart
));

#
# trusted-networks-modify
#
my $event = 'trusted-networks-modify';
templates2events("/etc/httpd/conf.d/zzz_bareos-webui.conf", $event);
event_services($event, 'httpd' => 'reload');
