#!/bin/bash

# Stop bareos instance
systemctl stop bareos-dir bareos-sd bareos-fd

if [ -f /var/lib/nethserver/bareos/bareos.sql ]; then
    drop_sql=`mktemp`
    chown postgres:postgres $drop_sql
    # drop all existing connections to the db and block new ones
    echo "UPDATE pg_database SET datallowconn = 'false' WHERE datname = 'bareos';" >> $drop_sql
    echo "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'bareos';" >> $drop_sql
    # drop the db, then recreate it
    echo "DROP DATABASE bareos;" >> $drop_sql
    echo "DROP USER IF EXISTS bareos;" >> $drop_sql
    password=`perl -e "use NethServer::Password; print NethServer::Password::store('bareos');"`
    echo "CREATE database bareos; CREATE USER bareos WITH PASSWORD '$password'; GRANT ALL PRIVILEGES ON DATABASE bareos to bareos;" >> $drop_sql
    # allow new connections to db
    echo "UPDATE pg_database SET datallowconn = 'true' WHERE datname = 'bareos';" >> $drop_sql
    su - postgres -c "psql < $drop_sql" >/dev/null
    su - postgres -c "psql bareos < /var/lib/nethserver/bareos/bareos.sql" >/dev/null
    rm -f $drop_sql
fi
