#!/usr/bin/bash

#
# create the db and the user bareos
#

su - postgres -c "scl enable rh-postgresql12 -- psql --port=55434 -lqt | cut -d \| -f 1 | grep -q -w bareos"
if [ $? -eq 1 ]; then # database do not exists
    su - postgres  -c "export PGPORT=55434;scl enable rh-postgresql12 -- /usr/lib/bareos/scripts/create_bareos_database"
    su - postgres  -c "export PGPORT=55434;scl enable rh-postgresql12 -- /usr/lib/bareos/scripts/make_bareos_tables"
    su - postgres  -c "export PGPORT=55434;scl enable rh-postgresql12 -- /usr/lib/bareos/scripts/grant_bareos_privileges"
    password=`perl -e "use NethServer::Password; print NethServer::Password::store('bareos');"`
    tmp_sql=`mktemp`
    chmod a+r $tmp_sql
    cat << EOF > $tmp_sql
ALTER USER bareos WITH PASSWORD '$password';
EOF
    su - postgres  -c "scl enable rh-postgresql12 -- psql --port=55434 < $tmp_sql" >/dev/null
    rm -f $tmp_sql
fi
