#!/bin/bash

mkdir -p /var/lib/nethserver/bareos/
chown -R postgres:postgres /var/lib/nethserver/bareos
su - postgres -c "scl enable rh-postgresql12 -- pg_dump --port=55434 bareos > /var/lib/nethserver/bareos/bareos.sql"
chmod -R 600 /var/lib/nethserver/bareos/*
